# SPDX-License-Identifier: GPL-2.0
# FPGA : BigOrca
dtb-$(CONFIG_ARCH_ANDES) += a25_c1_d_dsp_noncoherent_ae350.dtb
dtb-$(CONFIG_ARCH_ANDES) += a27l2_c1_d_dsp_noncoherent_ae350.dtb
dtb-$(CONFIG_ARCH_ANDES) += a45_c1_d_dsp_noncoherent_ae350.dtb
dtb-$(CONFIG_ARCH_ANDES) += ax25_c1_d_dsp_noncoherent_ae350.dtb
dtb-$(CONFIG_ARCH_ANDES) += ax27l2_c1_d_dsp_noncoherent_ae350.dtb
dtb-$(CONFIG_ARCH_ANDES) += ax45_c1_d_dsp_noncoherent_ae350.dtb
dtb-$(CONFIG_ARCH_ANDES) += ax25mp_amp_c2_64_d_ae350.dtb

# FPGA : VCU118
dtb-$(CONFIG_ARCH_ANDES) += a25mp_c4_d_dsp_ae350.dtb
dtb-$(CONFIG_ARCH_ANDES) += a45mp_c4_d_dsp_ae350.dtb
dtb-$(CONFIG_ARCH_ANDES) += ax25mp_c4_d_dsp_ae350.dtb
dtb-$(CONFIG_ARCH_ANDES) += ax45mp_c4_d_dsp_ae350.dtb
dtb-$(CONFIG_ARCH_ANDES) += ax45mpv_c4_d_dsp_ae350.dtb
dtb-$(CONFIG_ARCH_ANDES) += ax45mp_c8_ae350.dtb

# FPGA : VU19P
dtb-$(CONFIG_ARCH_ANDES) += ax65mp_c2_d_ae350.dtb
obj-$(CONFIG_BUILTIN_DTB) += $(addsuffix .o, $(dtb-y))
