# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2023 Andes Technology Corporation.

obj-y	+= andes_sbi.o
obj-y	+= inject_init.o
obj-y	+= dcause.o
obj-y	+= trigger_module.o
obj-$(CONFIG_ANDES_PPMA)	+= ppma.o
obj-$(CONFIG_ANDES_ATCSMU)	+= atcsmu.o pm.o
